import AlexeyImg from '../images/unsplash_3TLl_97HNJo-2.jpg';
import MariaImg from '../images/unsplash_3TLl_97HNJo-3.jpg';
import EgorImg from '../images/unsplash_3TLl_97HNJo-4.jpg';
import DariaImg from '../images/unsplash_3TLl_97HNJo-5.jpg';
import none from '../images/unsplash_3TLl_97HNJo-6.jpg';
import PolinaImg from '../images/unsplash_3TLl_97HNJo.jpg';

const blogerInfo = [
    {
        image: PolinaImg,
        name: "Полина Скирда",
        insagram: "polina_skirda",
        bussines: "Лайфстайл, домохозяйка",
        subscribers: 43.7,
        stories: 7,
        salary_before: "50 000 - 70 000",
        salary_after: "700 000",
        review: "#",
        id: 1,
    },
    {
        image: AlexeyImg,
        name: "Алексей Куреленок",
        insagram: "kurelenokk",
        bussines: "Предприниматель, общественный деятель",
        subscribers: 78.1,
        stories: 15,
        salary_before: "150 000 - 200 000",
        salary_after: "1 800 000",
        review: "#",
        id: 2,
    },
    {
        image: MariaImg,
        name: "Мария Калинина",
        insagram: "kalininamariya",
        bussines: "Контент для слабослышащих, Лайфстайл, домохозяйка",
        subscribers: 54.1,
        stories: 15,
        salary_before: "300 000 - 500 000",
        salary_after: "7 300 000",
        review: "#",
        id: 3,
    },
    {
        image: EgorImg,
        name: "Егор Лесной",
        insagram: "egor_lesnoy",
        bussines: "Лайфстайл, саморазвитие, здоровый образ жизни",
        subscribers: 21.2,
        stories: 6,
        salary_before: "10 000 - 20 000",
        salary_after: "299 000",
        review: "#",
        id: 4,
    },
    {
        image: DariaImg,
        name: "Дарья Астахова",
        insagram: "dariaastakhova",
        bussines: "Лайфстайл, бьюти",
        subscribers: 39.9,
        stories: 4,
        salary_before: "50 000 - 70 000",
        salary_after: "380 000",
        review: "#",
        id: 5,
    },
    {
        image: none,
        name: "Галя",
        insagram: "-",
        bussines: "-",
        subscribers: "-",
        stories: "-",
        salary_before: "-",
        salary_after: "-",
        review: "#",
        id: 6,
    },
    {
        image: none,
        name: "Галя",
        insagram: "-",
        bussines: "-",
        subscribers: "-",
        stories: "-",
        salary_before: "-",
        salary_after: "-",
        review: "#",
        id: 7,
    },
]

export default blogerInfo;